"""add_group_action_associations

Revision ID: 89da06437857
Revises: 1ec275279a53
Create Date: 2026-01-27 22:18:40.887466

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '89da06437857'
down_revision: str | Sequence[str] | None = '1ec275279a53'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_action_definitions',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('definition_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['definition_id'], ['action_definitions.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_action_definitions_id'), 'group_action_definitions', ['id'], unique=False)
    op.add_column('action_records', sa.Column('group_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'action_records', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'action_records', type_='foreignkey')
    op.drop_column('action_records', 'group_id')
    op.drop_index(op.f('ix_group_action_definitions_id'), table_name='group_action_definitions')
    op.drop_table('group_action_definitions')
    # ### end Alembic commands ###
